/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.boot.App;
import com.boot.controller.HomeController;
import org.junit.Assert;
import org.junit.Test;

public class AppTest {



    final private String test = "Hello World";
    @Test
    public void testAppHasAGreeting() {
        HomeController homeController = new HomeController();
        Assert.assertEquals(homeController.home(),test);
    }
}
